name: Build Android

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Настройка Java (нужна для Gradle)
      - uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      # Flutter
      - name: Setup Flutter 3.38.3
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.38.3" # ← Важно именно эта версия
          channel: "stable"
          cache: true

      - name: Get dependencies
        run: |
          flutter pub get
        env:
          GPR_KEY: ${{ secrets.GPR_KEY }}

      - name: Code generation
        run: make gen

      # ==================== Подпись ====================
      - name: Generate Keystore
        run: |
          keytool -genkeypair -v \
            -keystore android/trusttunnel.keystore \
            -alias trusttunnel \
            -keyalg RSA -keysize 2048 -validity 10000 \
            -sigalg SHA256withRSA \
            -dname "CN=TrustTunnel, OU=Dev, O=TrustTunnel, L=, S=, C=RU" \
            -storepass ${{ secrets.ANDROID_KEYSTORE_PASSWORD }} \
            -keypass ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}

      - name: Create local.properties
        run: |
          cat > android/local.properties << EOF
          flutter.sdk=${FLUTTER_ROOT}
          flutter.versionCode=1
          flutter.versionName=1.2.0-custom
          signingConfigKeyAlias=trusttunnel
          signingConfigKeyPassword=${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          signingConfigKeyStorePath=./trusttunnel.keystore
          signingConfigKeyStorePassword=${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          EOF

      - name: Build Release APKs (split by ABI)
        run: flutter build apk --release --split-per-abi

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: TrustTunnel-APKs
          path: build/app/outputs/flutter-apk/*.apk
          retention-days: 30
